on:
  schedule:
    - cron: "0 0 * * *"  # Günlük çalıştırma
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # GitHub Stats'ı bir dosyaya yazdır
      - name: Generate GitHub Stats
        run: |
          curl -o github-stats.svg "https://github-readme-stats.vercel.app/api?username=ca1ik&show_icons=true&locale=en&count_private=true"
      
      # README.md dosyasını güncelle
      - name: Update README
        run: |
          echo "![GitHub Stats](github-stats.svg)" >> README.md
      
      # Commit ve Push işlemi
      - name: Commit and Push Changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add README.md
          git commit -m "Update GitHub Stats with Private Contributions"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.tokenX }}
