# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run.
on:
  schedule:
    # Runs every day at midnight
    - cron: "0 0 * * *"

  # Allows manual trigger from the Actions tab
  workflow_dispatch:

  # Runs on push to the specified branch
  push:
    branches:
      - main  # Update this if your branch is named "master"

# The sequence of runs in this workflow:
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5

    # Steps represent a sequence of tasks to execute
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Generate the snake
      - uses: Platane/snk/svg-only@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Show the status of the build for debugging
      - run: git status

      # Push the images to the output branch
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
